### ISSUE TITLE
v1.0 Roadmap

### ISSUE THREAD

**Issue by chenasraf** [chenasraf/text-transform.nvim#13]
Here I will keep a list of features I plan to add before I am able to consider this v1.0. When these are done they will be checked off. Might add some as time goes on.

## Wishlist

- [x] Use a different choosing mechanism (telescope)
- [x] ~~Add motions (changing to specific case)~~
  - [x] ~~Function to immediately transform word into a case by sequence~~
- [x] Sort menu items by usage frequency, name, etc
- [x] ~Transform on multiple separate columns~ (5765e3d72109c473b4f9ab8839d01f8c983d0dc2)
- [x] Ability to hide transformers from the menu
- [x] Ability to switch between telescope and other type of popup
- [ ] Re-doable actions
